export { default as ProfileSection } from './ProfileSection'
export { default as OrdersSection } from './OrdersSection'
export { default as WishlistSection } from './WishlistSection'
export { default as AddressesSection } from './AddressesSection'
export { default as SettingsSection } from './SettingsSection'