export { default as ProfileSection } from './ProfileSection'
export { default as ProfileOrdersSection } from './ProfileOrdersSection'
export { default as WishlistSection } from './WishlistSection'
export { default as AddressesSection } from './AddressesSection'
export { default as SettingsSection } from './SettingsSection'