# Generated by Django 5.2.8 on 2025-12-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='landing/featured_vehicles/')),
                ('hover_title', models.CharField(blank=True, help_text='Title shown on hover', max_length=200)),
                ('hover_description', models.TextField(blank=True, help_text='Description shown on hover')),
                ('link', models.URLField(blank=True, help_text='Link when card is clicked')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_banner', models.ForeignKey(help_text='Hero banner this vehicle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='featured_vehicles', to='landing.herobanner')),
            ],
            options={
                'verbose_name': 'Featured Vehicle',
                'verbose_name_plural': 'Featured Vehicles',
                'db_table': 'landing_featured_vehicles',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
