# Generated by Django 5.2.8 on 2025-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_featuredvehicle'),
        ('products', '0006_product_products_part_ca_a52758_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorysection',
            index=models.Index(fields=['category'], name='landing_cat_categor_9dd394_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysection',
            index=models.Index(fields=['is_active'], name='landing_cat_is_acti_14dc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysection',
            index=models.Index(fields=['category', 'is_active'], name='landing_cat_categor_fa77ed_idx'),
        ),
    ]
