# Generated by Django 5.2.8 on 2025-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_slug_5e91f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_sku_fe2039_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_brand_i_a054bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_part_ca_a52758_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_d79db5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_e1ba5f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='partcategory',
            unique_together={('parent', 'name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='compatibility_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='continue_selling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_per_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_part_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oem_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='track_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/featured/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/images/'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
