# Generated by Django 5.2.8 on 2025-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_slug_5e91f2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partcategory',
            index=models.Index(fields=['parent'], name='product_par_parent__c9b219_idx'),
        ),
        migrations.AddIndex(
            model_name='partcategory',
            index=models.Index(fields=['is_active'], name='product_par_is_acti_3878b6_idx'),
        ),
        migrations.AddIndex(
            model_name='partcategory',
            index=models.Index(fields=['parent', 'is_active'], name='product_par_parent__e87f36_idx'),
        ),
    ]
