# Generated by Django 5.2.8 on 2025-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_partcategory_product_par_parent__c9b219_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_category'], name='products_part_ca_a52758_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_category', 'is_active'], name='products_part_ca_eff675_idx'),
        ),
    ]
