# Generated by Django 5.2.8 on 2025-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='The FAQ answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the FAQ was created'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this FAQ is currently active and visible'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for the FAQ (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='The FAQ question', max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the FAQ was last updated'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Main content of the page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the page was created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this page is currently active and visible'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'About'), ('terms', 'Terms & Conditions'), ('refund', 'Return, Refund & Safety Tips'), ('privacy', 'Privacy Policy'), ('faq', 'FAQs')], help_text='Type/category of the page', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the page', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title of the page', max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the page was last updated'),
        ),
    ]
