# Generated by Django 5.2.7 on 2025-12-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of adding to cart', max_digits=10, null=True),
        ),
    ]
